### ISSUE TITLE
Think about encoding

### ISSUE THREAD

**Issue by krlmlr** [metacran/description#11]
Follow-up to https://github.com/hadley/devtools/pull/932#issuecomment-171332370.

If you want an accurate representation of the semantics of the DESCRIPTION file in your class, I think there's no way around decoding on input and encoding on output. Looks like this is what R does, too. This will be mostly relevant for author names, though.

**Comment by gaborcsardi** [comment]
I guess I can use the `Encoding` field in the file itself.

What if there is no `Encoding` and there are non-ascii characters? Warning message?

**Comment by krlmlr** [comment]
A warning looks appropriate to me.
