### ISSUE TITLE
"version" column in get_deps() and set_deps()

### ISSUE THREAD

**Issue by krlmlr** [metacran/description#12]
Tried to add a dependency with `NA` value in `version` column, the results were... interesting:

```
# devtools::install_github("krlmlr/tibble")
d$get_deps() %>% tibble::add_row(type = "Imports", package = "DBI") %>% d$set_deps()
```

It works as expected when I say `version = "*"`, though.

Will there be an `add_dep()` or even a `remove_dep()` function?

**Comment by gaborcsardi** [comment]
How about `set_dep()` and `del_dep()`? 
https://github.com/metacran/description/blob/ee87adc336ff4cd0c12c26a37dbb71c3515d8971/R/description.R#L123

**Comment by krlmlr** [comment]
Thanks, totally missed that. (Only looked briefly through the auto-completion list.)

**Comment by gaborcsardi** [comment]
No problem.
