### ISSUE TITLE
FR: Standardized order of entries

### ISSUE THREAD

**Issue by krlmlr** [metacran/description#15]
Makes a difference both in the printed manual, and also helps when editing the DESCRIPTION. Should be an option for writing, or a transformation of a description object

First draft:

1. Title
1. Description
1. Authors@R
1. Date
1. Version
1. License
1. BugReports, URL
1. Dependencies
1. LazyData, RoxygenNote, Encoding, etc.
1. Collate

Which fields have I missed?

**Comment by krlmlr** [comment]
Already implemented, at least for the output. Awesome!

**Comment by gaborcsardi** [comment]
:)

**Comment by krlmlr** [comment]
Actually, I think the desired order should be encoded in the standard_fields variable. Would simplify field_order().

**Comment by gaborcsardi** [comment]
Possibly. I have a vague memory that the order is the same as in the R sources, to make comparison and updating easy. But I am not sure if this was the case.

**Comment by gaborcsardi** [comment]
I don't mind, really. If it works now as it is, we shouldn't update it, I guess.

**Comment by krlmlr** [comment]
If there's a reason for maintaining the original order, I agree we shouldn't change that. Nitpick: The order is only fixed for the most important fields, I was wondering if there's a "universally sane" order in which DESCRIPTION fields should be arranged.

**Comment by gaborcsardi** [comment]
Universally sane order: I don't know. I think it is only worth doing the ordering for the most common fields, and the rest can be after in alphabetical or whatever order. :)
