### ISSUE TITLE
Depends after Imports?

### ISSUE THREAD

**Issue by krlmlr** [metacran/description#18]
Is there a specific reason why "Depends" is listed after "Imports" in dep_types? Also, why is "VignetteBuilder" not included?

An attempt to change this breaks tests, so I thought I'd ask before PRing ;-)

**Comment by gaborcsardi** [comment]
No reasons for either. `Depends` can come first, and you can include `VignetteBuilder` as well.

**Comment by gaborcsardi** [comment]
I think this is not very important. Nevertheless I'll include `VignetteBuilder` after the dependency fields.
