### ISSUE TITLE
Automatic forwarding to implementations

### ISSUE THREAD

**Issue by krlmlr** [metacran/description#19]
```
description <- R6Class("description",
  public = list(

    ## Either from a file, or from a character vector
    initialize = forward_to_impl(idesc_create),

    write = forward_to_impl(idesc_write),

    ....
```

Motivation: 		0f89b50.

Downside: Implementations need to be defined before the class.

Implementation: Similar to https://github.com/krlmlr/hms/blob/master/R/aaa-tools.R.

Interested?

OTOH, one might argue that this really belongs in R6:

```
description <- R6Class("description",
  public = list(

    ## Either from a file, or from a character vector
    initialize = idesc_create,

    write = idesc_write,

    ....
```

**Comment by gaborcsardi** [comment]
I think this is overkill.

The last solution probably won't work because of scoping. `idesc_write` won't have access to `public` and `private` imo.

But anyway, I think it is overkill, and I am fine with the current manual solution.
