### ISSUE TITLE
Validation (again)

### ISSUE THREAD

**Issue by gaborcsardi** [metacran/description#8]
So, the thing is, some fields are hard to validate. Take the `License` field as an example. In https://github.com/wch/r-source/blob/trunk/src/library/tools/R/license.R ~800 lines of code deal with this.

So I am unsure what to do. Options are:

1. Do not validate fields properly, just do some simple syntax checks. `R CMD check` will catch the rest.
2. Copy over the code from `tools`. :/
3. Call the (non-exported) functions in `tools`
4. Reimplement the checks that are in `tools`.
5. Ask CRAN (Kurt) to export some of these functions from `tools`.

1-4 are all bad options, for various reasons. 5 is unlikely to be successful. Right now I am leaning towards 3.

@hadley what do you think?

**Comment by hadley** [comment]
Personally, I'd go with 1.

**Comment by gaborcsardi** [comment]
Ok, let's do that for now.

**Comment by gaborcsardi** [comment]
Done.
